global:
  message: global environment of microservices !
  logging:
    level:
      root: INFO
  management:
    endpoints:
      web:
        exposure:
          include: health, info, refresh
    endpoint:
      health:
        show-details: always
