global:
  message: welcome to customer-service-dev
server:
  port: 8082
message: hello from dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
