global:
  message: welcome to order-service-dev
server:
  port: 8084
message: hello from order dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_dev
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
