global:
  message: welcome to order-service-dev
server:
  port: 8084
message: hello from order dev
spring:
  datasource:
    url: jdbc:mem:h2:order_master
    username: sa
    password:
    # url: jdbc:mysql://localhost:3306/order_master
    # username: ${DB_USERNAME}
    # password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
