global:
  message: welcome to order-service-prod
server:
  port: 8085
message: hello from ordeer prod
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prrod
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
